# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "base"
  
  # Automatically use root to login
  config.ssh.username = 'root'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = 'true'

  # Hostname
  config.vm.hostname = 'vagrant'

  config.vm.provider "vmware_fusion" do |v|
    # Customize the amount of memory on the VM:
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
    v.vmx["vhv.enable"] = "TRUE"
  end

  #Ensure that VMWare Tools recompiles kernel modules
  # when we update the linux images
  $fix_vmware_tools_script = <<SCRIPT
sed -i.bak 's/answer AUTO_KMODS_ENABLED_ANSWER no/answer AUTO_KMODS_ENABLED_ANSWER yes/g' /etc/vmware-tools/locations
sed -i 's/answer AUTO_KMODS_ENABLED no/answer AUTO_KMODS_ENABLED yes/g' /etc/vmware-tools/locations
SCRIPT

  Vagrant.configure(2) do |config|
    config.vm.provision "shell", inline: $fix_vmware_tools_script
  end
end
